
# application.yml
spring:
  application:
    name: member-api
  profiles:
    active: prod
  config:
    import:
      aws-parameterstore:

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info

